# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5516ce01af8776170473b596f2f16da1d5b55300fd24c2ebf3db95c3d8e81fe63b606d51bce83a9276037436bb70db23f6f56886788a1814576fc1ea5ce65a1

test:
  secret_key_base: c8677992c38b890d5157b3d54eb81657d5d66701652319d470dec2f2ca993977c91cd35e09779ea5aca0334ba66db19c4ab0ee8ecee85be5136d470133a869bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
